version: '3.6'

services:

  db:
    image: postgres:13-alpine
    restart: always
    command: [ "postgres", "-c", "logging_collector=on", "-c", "log_directory=/tmp/logs", "-c", "log_filename=postgresql.log", "-c", "log_statement=all" ]
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usermanagementdev
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - user-management

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

networks:
  user-management:
    driver: bridge

volumes:
  postgres:
    driver: local
  redis:
    driver: local
